### ISSUE TITLE
20+ Dependencies needed?

### ISSUE THREAD

**Issue by cblaze22** [StephenCleary/Disposables#2] opened 2017-08-27 22:46 UTC
Why with the newest version on Nuget do I have to install 20+ packages with this project?  I am using .NET 4.7.

![capture](https://user-images.githubusercontent.com/556494/29754672-faaf7e2e-8b57-11e7-9437-b5f75a3dd9fe.PNG)

**Comment by StephenCleary** [comment] 2017-08-28 01:14
I'm unable to repro this. I created a new .NET 4.7 console application project and a new .NET 4.7 class library project, and successfully installed Nito.Disposables 1.2.2. It only brought in the `System.Collections.Immutable` dependency, and not any of the ones in your screenshot.

Please ensure you are using the newest tooling. Visual Studio 15.3.2 / NuGet Package Manager 4.3.0.

**Comment by cblaze22** [comment] 2017-08-28 03:08
Well I went ahead and updated VS and I believe those dependencies went away but now trying to upgrade again and getting this error below now.  I will keep working on it but wanted to see if you had any suggestions.  
```
Could not load file or assembly 'Nito.Disposables' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
```

**Comment by StephenCleary** [comment] 2017-08-28 13:02
v1.2.2 added [public signing, which claims the assembly is strong-named but doesn't give it a signature](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md). This sounds weird but is actually the desired behavior. Previous versions did not have strong names at all.

Proper strong naming is not supported yet. What context are you loading this in?

Also, was an older version working? This library has never supported strong naming, so that would be odd.

**Comment by cblaze22** [comment] 2017-08-28 18:12
I am still still getting the option from upgrading from 1.1.0 to 1.2.2 and requesting to install all those extra dependencies when I should already have them using .NET 4.7.

**Comment by cblaze22** [comment] 2017-08-28 18:14
Is the dependency NETStandard.Library (>= 1.6.1) making me download all of these projects?  Why does that need to be a dependency?

**Comment by StephenCleary** [comment] 2017-08-28 18:47
The `NETStandard.Library` dependency is only for `netstandard1.0` platforms (not `netstandard2.0`), so it won't apply for NET47 projects if the tooling is up-to-date.

I tried again to repro your scenario by creating a NET47 library and installing v1.1.0. Since there was no `NETStandard.Library` dependency for v1.1.0 `net45`, that worked fine. Then I upgraded to v1.2.2, and since there is no `NETStandard.Library` dependency for v1.2.2 `netstandard2.0`, that also worked fine.

Can you reproduce this with a new NET47 project?

**Comment by cblaze22** [comment] 2017-08-28 21:55
Well I did a Update-Package -reinstall on the entire project, then did the update and it looks like it worked.  It updated without showing all those dependencies but I keep a ton more issues, and now that same error about the signing is back.. I am going to keep it at the 1.1.0 for now.

**Comment by cblaze22** [comment] 2017-08-28 21:56
Yes I did the console and it worked fine, but this is a dependency on TweetInvi so I have to use it.

**Comment by StephenCleary** [comment] 2017-08-28 23:33
It's very interesting that the reinstall worked. Very weird, too. It's not at all obvious to me how that could even work. Out of curiosity, do you have a diff on your csproj and/or packages.config that show how the reinstall changed things?

I'm also still interested in what environment you're running in. I assume it's some kind of custom plugin system. AFAIK, there are two kinds of runtime environments: those that verify strong names, and those that don't. If the environment verifies strong names, then Nito.Disposables v1.1.0 and v1.2.2 should both fail: v1.1.0 doesn't have a strong name at all, and v1.2.2 has a public-signed strong name (which would cause the error you're seeing). If the environment doesn't verify strong names, then Nito.Disposables v1.1.0 and v1.2.2 should both pass. It seems like your environment is verifying strong names, but only if the "signed" bit is set in the executable, which would make this "partial strong-name verification" useless in practice. I'm not aware of any environment with those semantics.

**Comment by cblaze22** [comment] 2017-08-28 23:35
Is the 1.2.2 using .NET Core?  I am using the older .NET framework.

**Comment by cblaze22** [comment] 2017-08-28 23:37
Alot of this stuff was happening with me, seems it maybe a bug with VS2015.

https://github.com/dotnet/corefx/issues/23229

**Comment by StephenCleary** [comment] 2017-08-28 23:39
No; Nito.Disposables is a netstandard library, which should run on both .NET Core and the .NET Framework.

You're on VS2015? Yes, I'm pretty sure that would do it. The dependencies issue, I mean. Doesn't explain the strong name error.

**Comment by mscrivo** [comment] 2017-09-08 16:23
I'm getting 

> Could not load file or assembly 'Nito.Disposables' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

as well after updating to 1.2.2 (from 1.0).  This is in the context of a web app running on .NET 4.6.2 with VS 15.3.3

**Comment by StephenCleary** [comment] 2017-09-08 17:29
Ah, I believe the problem is partially trusted AppDomains. They're [not supported by public signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md).

At this point, I'm going to revert the public signing. It was a mistake. You should be able to upgrade to the next version without issue.

**Comment by cblaze22** [comment] 2017-09-08 17:31
Can you let us know once this will be updated to Nuget?

**Comment by mscrivo** [comment] 2017-09-08 18:15
Thanks

**Comment by StephenCleary** [comment] 2017-09-09 12:49
Nito.Disposables v1.2.3 is now up. You should be able to install it in the next half hour or so.

I expect this will resolve both the dependencies issue and the strongnaming issue, so I'm going to close this issue. Feel free to reopen if the problems aren't resolved.

**Closed as completed by StephenCleary** 2017-09-09 12:49 UTC

**Comment by cblaze22** [comment] 2017-09-09 13:15
Got the update but now getting reference issues.  I believe there is something fundamentally wrong with the setup of this project compared to the original which needs to be addressed.  I have about 50 other nuget packages, and this is the only project I am having problems with.

```
Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by cblaze22** [comment] 2017-09-09 14:16
[https://stackoverflow.com/questions/38408167/could-not-load-file-or-assembly-system-net-http-version-4-0-0-0-culture-neutr](url)

Can you make sure the project is updated with references and not using old assemblies?

**Comment by StephenCleary** [comment] 2017-09-09 15:05
There's only one (explicit) dependency: `System.Collections.Immutable` v1.4.0, which is the most recent release. The netstandard tooling adds an implicit dependency (`NETStandard.Library` v1.6.1), which is only applied to older platforms.

I suspect your problem is due to VS2015 having outdated tooling. Can you ensure that you have:
1) The most recent NuGet client.
2) Installed the [.NET Standard Build Support extension](https://aka.ms/netstandard-build-support-netfx).

**Comment by cblaze22** [comment] 2017-09-09 15:14
I told you I upgraded to VS2017.  I just don't think it has to do with the tooling now, but the project itself. Again everything else works on upgrades except this project.  I can keep researching to see but we already saw this signing issue and there seems to be another.

**Comment by StephenCleary** [comment] 2017-09-09 15:24
This is one of the simplest projects: two targets, one dependency, a few code files - that's it. I've gone over the csproj manually a dozen times, and I just don't see anything wrong with it.

Did the tooling add a binding redirect for Nito.Disposables? If so, can you post it?

**Comment by cblaze22** [comment] 2017-09-09 15:37
Maybe this is just related to this project as a dependency in this one below.  The only reason it is being used is because TweetInvi is using it.  Thought you might want to view that project and see if anything sticks out.

[https://github.com/linvi/tweetinvi](url)

**Comment by StephenCleary** [comment] 2017-09-09 15:39
Ah, it depends on AsyncEx.Context. I'm updating AsyncEx with these same changes now.

**Comment by cblaze22** [comment] 2017-09-09 15:39
Yea I saw those too, but didn't think it to mention them.

**Comment by StephenCleary** [comment] 2017-09-09 15:44
Have you upgraded AsyncEx.Context?

That package is a bit unusual. It was its own package when I originally converted to netstandard, but since then it's become part of a collection of packages (part of AsyncEx). That's why there's a version jump from 1.1.0 to a prerelease 5.x version. So for this particular package, you can upgrade to v5 (prerelease); it's only prerelease because there are other packages in the collection that are in prerelease, and the collection as a whole synchronizes its version numbers now.

Does that make sense? I don't even know if I can follow it. :)

Anyway, the AsyncEx v5.0.0-pre-05 releases are going out now. I'd try upgrading the AsyncEx.Context dependency to that version in 10 minutes or so.

**Comment by cblaze22** [comment] 2017-09-09 18:22
Same problems.  Sticking with older versions until this is resolved.

```
System.IO.FileLoadException: 'Could not load file or assembly 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
```

**Comment by mscrivo** [comment] 2017-09-09 20:19
For the record, I tried all the new pre-releases, upgrading all Nito packages together.  I think we're using all 6? and things are working fine on my end finally.  Thanks @StephenCleary

**Comment by mscrivo** [comment] 2017-09-09 20:23
@cblaze22 you're likely running into this: https://github.com/dotnet/corefx/issues/23306 I spent days sorting that all out.  In the end I removed all System.* nuget packages and updated all binding redirects for those packages to point to the new ones provided with the tooling in VS 2017 15.3+

**Comment by cblaze22** [comment] 2017-09-09 20:58
Can you show me what you mean by updating all redirects?  Some of my Nuget packages require the System.* as a dependency so I have to install them I believe.  I also posted that issue link previously in this thread.

**Comment by cblaze22** [comment] 2017-09-09 20:58
Night = nuget

**Comment by cblaze22** [comment] 2017-09-10 13:52
So I did what the post mentioned in one of the posts by updating the redirectBinding to what is below and the site loaded.  I hope everything else works fine but I think we are good to go.

```
 <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
      </dependentAssembly>      
    </assemblyBinding>
```

**Comment by cblaze22** [comment] 2017-09-11 13:27
This actually didn't help but downloaded extra System.*.

**Comment by mscrivo** [comment] 2017-09-11 13:57
download from where?  It will pull in the System.* packages from the VS tooling into your local bin folder, if that's what you mean?  If you're talking about nuget wanting to still pull in those dependencies, yeah that's an ongoing problem which I hope they can fix.  If you switch your nuget refs to packageReferences instead of packages.config, I think that should fix it.  We weren't able to switch to packagesReferences because we rely on packages like EF that do not work with packageReference.
